2025-08-21 07:21:53,658 ERROR frappe Unable to load translations
Site: erpnext.localhost
Form Dict: {}
Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 102, in application
    init_request(request)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 178, in init_request
    frappe.init(site, sites_path=_sites_path, force=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 208, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 1040, in setup_module_map
    for module in get_module_list(app):
                  ~~~~~~~~~~~~~~~^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 881, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
                          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/utils/redis_wrapper.py", line 253, in hget
    value = generator()
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 190, in get_translations_from_apps
    translations.update(get_translations_from_csv(lang, app) or {})
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 202, in get_translations_from_csv
    os.path.join(frappe.get_app_path(app, "translations"), lang + ".csv"), lang, app
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
2025-08-21 07:21:53,663 ERROR frappe Unable to load translations
Site: erpnext.localhost
Form Dict: {}
Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 102, in application
    init_request(request)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 178, in init_request
    frappe.init(site, sites_path=_sites_path, force=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 208, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 1040, in setup_module_map
    for module in get_module_list(app):
                  ~~~~~~~~~~~~~~~^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 881, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
                          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/utils/redis_wrapper.py", line 253, in hget
    value = generator()
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 190, in get_translations_from_apps
    translations.update(get_translations_from_csv(lang, app) or {})
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 202, in get_translations_from_csv
    os.path.join(frappe.get_app_path(app, "translations"), lang + ".csv"), lang, app
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext'
2025-08-21 23:58:20,151 ERROR frappe New Exception collected in error log
Site: erpnext.localhost
Form Dict: {'doctype': 'Website Settings', 'name': 'Website Settings', 'user': '', 'permission_to': 'read', 'value': '1', 'everyone': '1', 'cmd': 'frappe.share.set_permission'}
2025-08-26 21:13:14,216 ERROR frappe Unable to load translations
Site: erpnext.localhost
Form Dict: {}
Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 102, in application
    init_request(request)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 178, in init_request
    frappe.init(site, sites_path=_sites_path, force=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 208, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 1040, in setup_module_map
    for module in get_module_list(app):
                  ~~~~~~~~~~~~~~~^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 881, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
                          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'payments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/utils/redis_wrapper.py", line 253, in hget
    value = generator()
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 190, in get_translations_from_apps
    translations.update(get_translations_from_csv(lang, app) or {})
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 202, in get_translations_from_csv
    os.path.join(frappe.get_app_path(app, "translations"), lang + ".csv"), lang, app
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'payments'
2025-08-26 21:13:14,219 ERROR frappe Unable to load translations
Site: erpnext.localhost
Form Dict: {}
Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 102, in application
    init_request(request)
    ~~~~~~~~~~~~^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/app.py", line 178, in init_request
    frappe.init(site, sites_path=_sites_path, force=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 208, in init
    setup_module_map(include_all_apps=not (frappe.request or frappe.job or frappe.flags.in_migrate))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 1040, in setup_module_map
    for module in get_module_list(app):
                  ~~~~~~~~~~~~~~~^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 881, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
                          ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'payments'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 174, in get_all_translations
    return frappe.cache.hget(MERGED_TRANSLATION_KEY, lang, generator=_merge_translations)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/utils/redis_wrapper.py", line 253, in hget
    value = generator()
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 162, in _merge_translations
    all_translations.update(get_translations_from_apps(lang))
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 190, in get_translations_from_apps
    translations.update(get_translations_from_csv(lang, app) or {})
                        ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/translate.py", line 202, in get_translations_from_csv
    os.path.join(frappe.get_app_path(app, "translations"), lang + ".csv"), lang, app
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 846, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 876, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/mohammednishamnk/Documents/works/startecht/apps/frappe/frappe/__init__.py", line 817, in get_module
    return importlib.import_module(modulename)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'payments'
